# Generated by Django 6.0.7 on 2026-07-25 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('report_version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Generated', 'Generated'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='parser.resume')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
