# Generated by Django 6.0.7 on 2026-07-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ats_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='match_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='parsed_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='recommendations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Generated', 'Generated'), ('Downloaded', 'Downloaded'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
