# Generated by Django 6.0.7 on 2026-07-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_jobmatch_delete_resumeanalysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmatch',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='jobmatch',
            name='match_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='jobmatch',
            name='matched_skills',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='jobmatch',
            name='missing_skills',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='jobmatch',
            name='recommendations',
            field=models.JSONField(default=list),
        ),
    ]
