# Generated by Django 6.0.7 on 2026-07-31 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_remove_jobmatch_updated_at_and_more'),
        ('parser', '0006_alter_resume_extracted_text_alter_resume_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATSAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_score', models.PositiveIntegerField(default=0)),
                ('keyword_score', models.PositiveIntegerField(default=0)),
                ('skill_score', models.PositiveIntegerField(default=0)),
                ('education_score', models.PositiveIntegerField(default=0)),
                ('experience_score', models.PositiveIntegerField(default=0)),
                ('project_score', models.PositiveIntegerField(default=0)),
                ('certification_score', models.PositiveIntegerField(default=0)),
                ('format_score', models.PositiveIntegerField(default=0)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ats_analysis', to='parser.resume')),
            ],
            options={
                'verbose_name': 'ATS Analysis',
                'verbose_name_plural': 'ATS Analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.DeleteModel(
            name='JobMatch',
        ),
    ]
