# Generated by Django 6.0.7 on 2026-08-01 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_atsanalysis_delete_jobmatch'),
        ('parser', '0006_alter_resume_extracted_text_alter_resume_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atsanalysis',
            options={'ordering': ['-analyzed_at']},
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, default='', max_length=255)),
                ('job_description', models.TextField()),
                ('match_score', models.PositiveIntegerField(default=0)),
                ('match_level', models.CharField(blank=True, default='', max_length=30)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('extra_skills', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='parser.resume')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
