# Generated by Django 6.0.7 on 2026-08-01 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parser', '0006_alter_resume_extracted_text_alter_resume_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_roles', models.JSONField(blank=True, default=list)),
                ('recommended_skills', models.JSONField(blank=True, default=list)),
                ('recommended_courses', models.JSONField(blank=True, default=list)),
                ('recommended_projects', models.JSONField(blank=True, default=list)),
                ('learning_roadmap', models.JSONField(blank=True, default=list)),
                ('resume_tips', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='parser.resume')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
