# Generated by Django 6.0.7 on 2026-07-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='title',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='resume',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
    ]
