# Generated by Django 6.0.7 on 2026-07-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_alter_resume_options_resume_ats_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='recommendations',
            new_name='ai_recommendations',
        ),
    ]
